# Auto-generated from vendored Apple headers — do not edit manually.
# Regenerate with: nim r tools/generate_api.nim


import runtime
export runtime

type
  MTLPixelFormat* = uint
  MTLPrimitiveType* = uint
  MTLLoadAction* = uint
  MTLStoreAction* = uint
  MTLBlendFactor* = uint
  MTLBlendOperation* = uint
  MTLSamplerMinMagFilter* = uint
  MTLSamplerMipFilter* = uint
  MTLSamplerAddressMode* = uint
  MTLTextureUsage* = uint
  MTLCompareFunction* = uint
  MTLWinding* = uint
  MTLCullMode* = uint

const
  MTLPixelFormatInvalid*: MTLPixelFormat = 0
  MTLPixelFormatA8Unorm*: MTLPixelFormat = 1
  MTLPixelFormatR8Unorm*: MTLPixelFormat = 10
  MTLPixelFormatR8Unorm_sRGB*: MTLPixelFormat = 11
  MTLPixelFormatR8Snorm*: MTLPixelFormat = 12
  MTLPixelFormatR8Uint*: MTLPixelFormat = 13
  MTLPixelFormatR8Sint*: MTLPixelFormat = 14
  MTLPixelFormatR16Unorm*: MTLPixelFormat = 20
  MTLPixelFormatR16Snorm*: MTLPixelFormat = 22
  MTLPixelFormatR16Uint*: MTLPixelFormat = 23
  MTLPixelFormatR16Sint*: MTLPixelFormat = 24
  MTLPixelFormatR16Float*: MTLPixelFormat = 25
  MTLPixelFormatRG8Unorm*: MTLPixelFormat = 30
  MTLPixelFormatRG8Unorm_sRGB*: MTLPixelFormat = 31
  MTLPixelFormatRG8Snorm*: MTLPixelFormat = 32
  MTLPixelFormatRG8Uint*: MTLPixelFormat = 33
  MTLPixelFormatRG8Sint*: MTLPixelFormat = 34
  MTLPixelFormatB5G6R5Unorm*: MTLPixelFormat = 40
  MTLPixelFormatA1BGR5Unorm*: MTLPixelFormat = 41
  MTLPixelFormatABGR4Unorm*: MTLPixelFormat = 42
  MTLPixelFormatBGR5A1Unorm*: MTLPixelFormat = 43
  MTLPixelFormatR32Uint*: MTLPixelFormat = 53
  MTLPixelFormatR32Sint*: MTLPixelFormat = 54
  MTLPixelFormatR32Float*: MTLPixelFormat = 55
  MTLPixelFormatRG16Unorm*: MTLPixelFormat = 60
  MTLPixelFormatRG16Snorm*: MTLPixelFormat = 62
  MTLPixelFormatRG16Uint*: MTLPixelFormat = 63
  MTLPixelFormatRG16Sint*: MTLPixelFormat = 64
  MTLPixelFormatRG16Float*: MTLPixelFormat = 65
  MTLPixelFormatRGBA8Unorm*: MTLPixelFormat = 70
  MTLPixelFormatRGBA8Unorm_sRGB*: MTLPixelFormat = 71
  MTLPixelFormatRGBA8Snorm*: MTLPixelFormat = 72
  MTLPixelFormatRGBA8Uint*: MTLPixelFormat = 73
  MTLPixelFormatRGBA8Sint*: MTLPixelFormat = 74
  MTLPixelFormatBGRA8Unorm*: MTLPixelFormat = 80
  MTLPixelFormatBGRA8Unorm_sRGB*: MTLPixelFormat = 81
  MTLPixelFormatRGB10A2Unorm*: MTLPixelFormat = 90
  MTLPixelFormatRGB10A2Uint*: MTLPixelFormat = 91
  MTLPixelFormatRG11B10Float*: MTLPixelFormat = 92
  MTLPixelFormatRGB9E5Float*: MTLPixelFormat = 93
  MTLPixelFormatBGR10A2Unorm*: MTLPixelFormat = 94
  MTLPixelFormatBGR10_XR*: MTLPixelFormat = 554
  MTLPixelFormatBGR10_XR_sRGB*: MTLPixelFormat = 555
  MTLPixelFormatRG32Uint*: MTLPixelFormat = 103
  MTLPixelFormatRG32Sint*: MTLPixelFormat = 104
  MTLPixelFormatRG32Float*: MTLPixelFormat = 105
  MTLPixelFormatRGBA16Unorm*: MTLPixelFormat = 110
  MTLPixelFormatRGBA16Snorm*: MTLPixelFormat = 112
  MTLPixelFormatRGBA16Uint*: MTLPixelFormat = 113
  MTLPixelFormatRGBA16Sint*: MTLPixelFormat = 114
  MTLPixelFormatRGBA16Float*: MTLPixelFormat = 115
  MTLPixelFormatBGRA10_XR*: MTLPixelFormat = 552
  MTLPixelFormatBGRA10_XR_sRGB*: MTLPixelFormat = 553
  MTLPixelFormatRGBA32Uint*: MTLPixelFormat = 123
  MTLPixelFormatRGBA32Sint*: MTLPixelFormat = 124
  MTLPixelFormatRGBA32Float*: MTLPixelFormat = 125
  MTLPixelFormatBC1_RGBA*: MTLPixelFormat = 130
  MTLPixelFormatBC1_RGBA_sRGB*: MTLPixelFormat = 131
  MTLPixelFormatBC2_RGBA*: MTLPixelFormat = 132
  MTLPixelFormatBC2_RGBA_sRGB*: MTLPixelFormat = 133
  MTLPixelFormatBC3_RGBA*: MTLPixelFormat = 134
  MTLPixelFormatBC3_RGBA_sRGB*: MTLPixelFormat = 135
  MTLPixelFormatBC4_RUnorm*: MTLPixelFormat = 140
  MTLPixelFormatBC4_RSnorm*: MTLPixelFormat = 141
  MTLPixelFormatBC5_RGUnorm*: MTLPixelFormat = 142
  MTLPixelFormatBC5_RGSnorm*: MTLPixelFormat = 143
  MTLPixelFormatBC6H_RGBFloat*: MTLPixelFormat = 150
  MTLPixelFormatBC6H_RGBUfloat*: MTLPixelFormat = 151
  MTLPixelFormatBC7_RGBAUnorm*: MTLPixelFormat = 152
  MTLPixelFormatBC7_RGBAUnorm_sRGB*: MTLPixelFormat = 153
  MTLPixelFormatPVRTC_RGB_2BPP*: MTLPixelFormat = 160
  MTLPixelFormatPVRTC_RGB_2BPP_sRGB*: MTLPixelFormat = 161
  MTLPixelFormatPVRTC_RGB_4BPP*: MTLPixelFormat = 162
  MTLPixelFormatPVRTC_RGB_4BPP_sRGB*: MTLPixelFormat = 163
  MTLPixelFormatPVRTC_RGBA_2BPP*: MTLPixelFormat = 164
  MTLPixelFormatPVRTC_RGBA_2BPP_sRGB*: MTLPixelFormat = 165
  MTLPixelFormatPVRTC_RGBA_4BPP*: MTLPixelFormat = 166
  MTLPixelFormatPVRTC_RGBA_4BPP_sRGB*: MTLPixelFormat = 167
  MTLPixelFormatEAC_R11Unorm*: MTLPixelFormat = 170
  MTLPixelFormatEAC_R11Snorm*: MTLPixelFormat = 172
  MTLPixelFormatEAC_RG11Unorm*: MTLPixelFormat = 174
  MTLPixelFormatEAC_RG11Snorm*: MTLPixelFormat = 176
  MTLPixelFormatEAC_RGBA8*: MTLPixelFormat = 178
  MTLPixelFormatEAC_RGBA8_sRGB*: MTLPixelFormat = 179
  MTLPixelFormatETC2_RGB8*: MTLPixelFormat = 180
  MTLPixelFormatETC2_RGB8_sRGB*: MTLPixelFormat = 181
  MTLPixelFormatETC2_RGB8A1*: MTLPixelFormat = 182
  MTLPixelFormatETC2_RGB8A1_sRGB*: MTLPixelFormat = 183
  MTLPixelFormatASTC_4x4_sRGB*: MTLPixelFormat = 186
  MTLPixelFormatASTC_5x4_sRGB*: MTLPixelFormat = 187
  MTLPixelFormatASTC_5x5_sRGB*: MTLPixelFormat = 188
  MTLPixelFormatASTC_6x5_sRGB*: MTLPixelFormat = 189
  MTLPixelFormatASTC_6x6_sRGB*: MTLPixelFormat = 190
  MTLPixelFormatASTC_8x5_sRGB*: MTLPixelFormat = 192
  MTLPixelFormatASTC_8x6_sRGB*: MTLPixelFormat = 193
  MTLPixelFormatASTC_8x8_sRGB*: MTLPixelFormat = 194
  MTLPixelFormatASTC_10x5_sRGB*: MTLPixelFormat = 195
  MTLPixelFormatASTC_10x6_sRGB*: MTLPixelFormat = 196
  MTLPixelFormatASTC_10x8_sRGB*: MTLPixelFormat = 197
  MTLPixelFormatASTC_10x10_sRGB*: MTLPixelFormat = 198
  MTLPixelFormatASTC_12x10_sRGB*: MTLPixelFormat = 199
  MTLPixelFormatASTC_12x12_sRGB*: MTLPixelFormat = 200
  MTLPixelFormatASTC_4x4_LDR*: MTLPixelFormat = 204
  MTLPixelFormatASTC_5x4_LDR*: MTLPixelFormat = 205
  MTLPixelFormatASTC_5x5_LDR*: MTLPixelFormat = 206
  MTLPixelFormatASTC_6x5_LDR*: MTLPixelFormat = 207
  MTLPixelFormatASTC_6x6_LDR*: MTLPixelFormat = 208
  MTLPixelFormatASTC_8x5_LDR*: MTLPixelFormat = 210
  MTLPixelFormatASTC_8x6_LDR*: MTLPixelFormat = 211
  MTLPixelFormatASTC_8x8_LDR*: MTLPixelFormat = 212
  MTLPixelFormatASTC_10x5_LDR*: MTLPixelFormat = 213
  MTLPixelFormatASTC_10x6_LDR*: MTLPixelFormat = 214
  MTLPixelFormatASTC_10x8_LDR*: MTLPixelFormat = 215
  MTLPixelFormatASTC_10x10_LDR*: MTLPixelFormat = 216
  MTLPixelFormatASTC_12x10_LDR*: MTLPixelFormat = 217
  MTLPixelFormatASTC_12x12_LDR*: MTLPixelFormat = 218
  MTLPixelFormatASTC_4x4_HDR*: MTLPixelFormat = 222
  MTLPixelFormatASTC_5x4_HDR*: MTLPixelFormat = 223
  MTLPixelFormatASTC_5x5_HDR*: MTLPixelFormat = 224
  MTLPixelFormatASTC_6x5_HDR*: MTLPixelFormat = 225
  MTLPixelFormatASTC_6x6_HDR*: MTLPixelFormat = 226
  MTLPixelFormatASTC_8x5_HDR*: MTLPixelFormat = 228
  MTLPixelFormatASTC_8x6_HDR*: MTLPixelFormat = 229
  MTLPixelFormatASTC_8x8_HDR*: MTLPixelFormat = 230
  MTLPixelFormatASTC_10x5_HDR*: MTLPixelFormat = 231
  MTLPixelFormatASTC_10x6_HDR*: MTLPixelFormat = 232
  MTLPixelFormatASTC_10x8_HDR*: MTLPixelFormat = 233
  MTLPixelFormatASTC_10x10_HDR*: MTLPixelFormat = 234
  MTLPixelFormatASTC_12x10_HDR*: MTLPixelFormat = 235
  MTLPixelFormatASTC_12x12_HDR*: MTLPixelFormat = 236
  MTLPixelFormatGBGR422*: MTLPixelFormat = 240
  MTLPixelFormatBGRG422*: MTLPixelFormat = 241
  MTLPixelFormatDepth16Unorm*: MTLPixelFormat = 250
  MTLPixelFormatDepth32Float*: MTLPixelFormat = 252
  MTLPixelFormatStencil8*: MTLPixelFormat = 253
  MTLPixelFormatDepth24Unorm_Stencil8*: MTLPixelFormat = 255
  MTLPixelFormatDepth32Float_Stencil8*: MTLPixelFormat = 260
  MTLPixelFormatX32_Stencil8*: MTLPixelFormat = 261
  MTLPixelFormatX24_Stencil8*: MTLPixelFormat = 262
  MTLPrimitiveTypePoint*: MTLPrimitiveType = 0
  MTLPrimitiveTypeLine*: MTLPrimitiveType = 1
  MTLPrimitiveTypeLineStrip*: MTLPrimitiveType = 2
  MTLPrimitiveTypeTriangle*: MTLPrimitiveType = 3
  MTLPrimitiveTypeTriangleStrip*: MTLPrimitiveType = 4
  MTLLoadActionDontCare*: MTLLoadAction = 0
  MTLLoadActionLoad*: MTLLoadAction = 1
  MTLLoadActionClear*: MTLLoadAction = 2
  MTLStoreActionDontCare*: MTLStoreAction = 0
  MTLStoreActionStore*: MTLStoreAction = 1
  MTLStoreActionMultisampleResolve*: MTLStoreAction = 2
  MTLStoreActionStoreAndMultisampleResolve*: MTLStoreAction = 3
  MTLStoreActionUnknown*: MTLStoreAction = 4
  MTLStoreActionCustomSampleDepthStore*: MTLStoreAction = 5
  MTLBlendFactorZero*: MTLBlendFactor = 0
  MTLBlendFactorOne*: MTLBlendFactor = 1
  MTLBlendFactorSourceColor*: MTLBlendFactor = 2
  MTLBlendFactorOneMinusSourceColor*: MTLBlendFactor = 3
  MTLBlendFactorSourceAlpha*: MTLBlendFactor = 4
  MTLBlendFactorOneMinusSourceAlpha*: MTLBlendFactor = 5
  MTLBlendFactorDestinationColor*: MTLBlendFactor = 6
  MTLBlendFactorOneMinusDestinationColor*: MTLBlendFactor = 7
  MTLBlendFactorDestinationAlpha*: MTLBlendFactor = 8
  MTLBlendFactorOneMinusDestinationAlpha*: MTLBlendFactor = 9
  MTLBlendFactorSourceAlphaSaturated*: MTLBlendFactor = 10
  MTLBlendFactorBlendColor*: MTLBlendFactor = 11
  MTLBlendFactorOneMinusBlendColor*: MTLBlendFactor = 12
  MTLBlendFactorBlendAlpha*: MTLBlendFactor = 13
  MTLBlendFactorOneMinusBlendAlpha*: MTLBlendFactor = 14
  MTLBlendFactorSource1Color*: MTLBlendFactor = 15
  MTLBlendFactorOneMinusSource1Color*: MTLBlendFactor = 16
  MTLBlendFactorSource1Alpha*: MTLBlendFactor = 17
  MTLBlendFactorOneMinusSource1Alpha*: MTLBlendFactor = 18
  MTLBlendOperationAdd*: MTLBlendOperation = 0
  MTLBlendOperationSubtract*: MTLBlendOperation = 1
  MTLBlendOperationReverseSubtract*: MTLBlendOperation = 2
  MTLBlendOperationMin*: MTLBlendOperation = 3
  MTLBlendOperationMax*: MTLBlendOperation = 4
  MTLSamplerMinMagFilterNearest*: MTLSamplerMinMagFilter = 0
  MTLSamplerMinMagFilterLinear*: MTLSamplerMinMagFilter = 1
  MTLSamplerMipFilterNotMipmapped*: MTLSamplerMipFilter = 0
  MTLSamplerMipFilterNearest*: MTLSamplerMipFilter = 1
  MTLSamplerMipFilterLinear*: MTLSamplerMipFilter = 2
  MTLSamplerAddressModeClampToEdge*: MTLSamplerAddressMode = 0
  MTLSamplerAddressModeMirrorClampToEdge*: MTLSamplerAddressMode = 1
  MTLSamplerAddressModeRepeat*: MTLSamplerAddressMode = 2
  MTLSamplerAddressModeMirrorRepeat*: MTLSamplerAddressMode = 3
  MTLSamplerAddressModeClampToZero*: MTLSamplerAddressMode = 4
  MTLSamplerAddressModeClampToBorderColor*: MTLSamplerAddressMode = 5
  MTLTextureUsageUnknown*: MTLTextureUsage = 0x0000
  MTLTextureUsageShaderRead*: MTLTextureUsage = 0x0001
  MTLTextureUsageShaderWrite*: MTLTextureUsage = 0x0002
  MTLTextureUsageRenderTarget*: MTLTextureUsage = 0x0004
  MTLTextureUsagePixelFormatView*: MTLTextureUsage = 0x0010
  MTLTextureUsageShaderAtomic*: MTLTextureUsage = 0x0020
  MTLCompareFunctionNever*: MTLCompareFunction = 0
  MTLCompareFunctionLess*: MTLCompareFunction = 1
  MTLCompareFunctionEqual*: MTLCompareFunction = 2
  MTLCompareFunctionLessEqual*: MTLCompareFunction = 3
  MTLCompareFunctionGreater*: MTLCompareFunction = 4
  MTLCompareFunctionNotEqual*: MTLCompareFunction = 5
  MTLCompareFunctionGreaterEqual*: MTLCompareFunction = 6
  MTLCompareFunctionAlways*: MTLCompareFunction = 7
  MTLWindingClockwise*: MTLWinding = 0
  MTLWindingCounterClockwise*: MTLWinding = 1
  MTLCullModeNone*: MTLCullMode = 0
  MTLCullModeFront*: MTLCullMode = 1
  MTLCullModeBack*: MTLCullMode = 2
